version: '3.7'

services:
  # react-dev:
  #   depends_on:
  #       - "ganache"
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - './src/:/app/src'
  #   container_name: react
  #   ports:
  #     - '3000:3000'

  ganache:
    build:
        context: .
        dockerfile: Dockerfile.ganache
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider
    container_name: ganache
    ports:
      - "8545:8545"
